// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: detective.proto

package detectivev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_SendSnapshot_FullMethodName = "/detective.v1.AgentService/SendSnapshot"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	SendSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) SendSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, AgentService_SendSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	SendSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) SendSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSnapshot not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_SendSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SendSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SendSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SendSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "detective.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSnapshot",
			Handler:    _AgentService_SendSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "detective.proto",
}

const (
	DetectiveService_GetFlows_FullMethodName   = "/detective.v1.DetectiveService/GetFlows"
	DetectiveService_GetTop_FullMethodName     = "/detective.v1.DetectiveService/GetTop"
	DetectiveService_GetRetrans_FullMethodName = "/detective.v1.DetectiveService/GetRetrans"
	DetectiveService_GetLatency_FullMethodName = "/detective.v1.DetectiveService/GetLatency"
	DetectiveService_GetDNS_FullMethodName     = "/detective.v1.DetectiveService/GetDNS"
)

// DetectiveServiceClient is the client API for DetectiveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DetectiveServiceClient interface {
	GetFlows(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FlowList, error)
	GetTop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TopTalkerList, error)
	GetRetrans(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RetransList, error)
	GetLatency(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LatencyList, error)
	GetDNS(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DNSList, error)
}

type detectiveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDetectiveServiceClient(cc grpc.ClientConnInterface) DetectiveServiceClient {
	return &detectiveServiceClient{cc}
}

func (c *detectiveServiceClient) GetFlows(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FlowList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlowList)
	err := c.cc.Invoke(ctx, DetectiveService_GetFlows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectiveServiceClient) GetTop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TopTalkerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopTalkerList)
	err := c.cc.Invoke(ctx, DetectiveService_GetTop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectiveServiceClient) GetRetrans(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RetransList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetransList)
	err := c.cc.Invoke(ctx, DetectiveService_GetRetrans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectiveServiceClient) GetLatency(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LatencyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LatencyList)
	err := c.cc.Invoke(ctx, DetectiveService_GetLatency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectiveServiceClient) GetDNS(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DNSList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DNSList)
	err := c.cc.Invoke(ctx, DetectiveService_GetDNS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetectiveServiceServer is the server API for DetectiveService service.
// All implementations must embed UnimplementedDetectiveServiceServer
// for forward compatibility.
type DetectiveServiceServer interface {
	GetFlows(context.Context, *Empty) (*FlowList, error)
	GetTop(context.Context, *Empty) (*TopTalkerList, error)
	GetRetrans(context.Context, *Empty) (*RetransList, error)
	GetLatency(context.Context, *Empty) (*LatencyList, error)
	GetDNS(context.Context, *Empty) (*DNSList, error)
	mustEmbedUnimplementedDetectiveServiceServer()
}

// UnimplementedDetectiveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDetectiveServiceServer struct{}

func (UnimplementedDetectiveServiceServer) GetFlows(context.Context, *Empty) (*FlowList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFlows not implemented")
}
func (UnimplementedDetectiveServiceServer) GetTop(context.Context, *Empty) (*TopTalkerList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTop not implemented")
}
func (UnimplementedDetectiveServiceServer) GetRetrans(context.Context, *Empty) (*RetransList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRetrans not implemented")
}
func (UnimplementedDetectiveServiceServer) GetLatency(context.Context, *Empty) (*LatencyList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatency not implemented")
}
func (UnimplementedDetectiveServiceServer) GetDNS(context.Context, *Empty) (*DNSList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDNS not implemented")
}
func (UnimplementedDetectiveServiceServer) mustEmbedUnimplementedDetectiveServiceServer() {}
func (UnimplementedDetectiveServiceServer) testEmbeddedByValue()                          {}

// UnsafeDetectiveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DetectiveServiceServer will
// result in compilation errors.
type UnsafeDetectiveServiceServer interface {
	mustEmbedUnimplementedDetectiveServiceServer()
}

func RegisterDetectiveServiceServer(s grpc.ServiceRegistrar, srv DetectiveServiceServer) {
	// If the following call panics, it indicates UnimplementedDetectiveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DetectiveService_ServiceDesc, srv)
}

func _DetectiveService_GetFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectiveServiceServer).GetFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectiveService_GetFlows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectiveServiceServer).GetFlows(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectiveService_GetTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectiveServiceServer).GetTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectiveService_GetTop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectiveServiceServer).GetTop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectiveService_GetRetrans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectiveServiceServer).GetRetrans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectiveService_GetRetrans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectiveServiceServer).GetRetrans(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectiveService_GetLatency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectiveServiceServer).GetLatency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectiveService_GetLatency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectiveServiceServer).GetLatency(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectiveService_GetDNS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectiveServiceServer).GetDNS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectiveService_GetDNS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectiveServiceServer).GetDNS(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DetectiveService_ServiceDesc is the grpc.ServiceDesc for DetectiveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DetectiveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "detective.v1.DetectiveService",
	HandlerType: (*DetectiveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFlows",
			Handler:    _DetectiveService_GetFlows_Handler,
		},
		{
			MethodName: "GetTop",
			Handler:    _DetectiveService_GetTop_Handler,
		},
		{
			MethodName: "GetRetrans",
			Handler:    _DetectiveService_GetRetrans_Handler,
		},
		{
			MethodName: "GetLatency",
			Handler:    _DetectiveService_GetLatency_Handler,
		},
		{
			MethodName: "GetDNS",
			Handler:    _DetectiveService_GetDNS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "detective.proto",
}
