// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: detective.proto

package detectivev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlowEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIp         []byte                 `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp         []byte                 `protobuf:"bytes,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort       uint32                 `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort       uint32                 `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Pid           uint32                 `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	Comm          string                 `protobuf:"bytes,6,opt,name=comm,proto3" json:"comm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowEvent) Reset() {
	*x = FlowEvent{}
	mi := &file_detective_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowEvent) ProtoMessage() {}

func (x *FlowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowEvent.ProtoReflect.Descriptor instead.
func (*FlowEvent) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{0}
}

func (x *FlowEvent) GetSrcIp() []byte {
	if x != nil {
		return x.SrcIp
	}
	return nil
}

func (x *FlowEvent) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *FlowEvent) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *FlowEvent) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *FlowEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *FlowEvent) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

type ThroughputEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIp         []byte                 `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp         []byte                 `protobuf:"bytes,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort       uint32                 `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort       uint32                 `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,5,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,6,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThroughputEntry) Reset() {
	*x = ThroughputEntry{}
	mi := &file_detective_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThroughputEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThroughputEntry) ProtoMessage() {}

func (x *ThroughputEntry) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThroughputEntry.ProtoReflect.Descriptor instead.
func (*ThroughputEntry) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{1}
}

func (x *ThroughputEntry) GetSrcIp() []byte {
	if x != nil {
		return x.SrcIp
	}
	return nil
}

func (x *ThroughputEntry) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *ThroughputEntry) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *ThroughputEntry) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *ThroughputEntry) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *ThroughputEntry) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

type RetransEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIp         []byte                 `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp         []byte                 `protobuf:"bytes,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort       uint32                 `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort       uint32                 `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Count         uint64                 `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetransEntry) Reset() {
	*x = RetransEntry{}
	mi := &file_detective_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetransEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetransEntry) ProtoMessage() {}

func (x *RetransEntry) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetransEntry.ProtoReflect.Descriptor instead.
func (*RetransEntry) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{2}
}

func (x *RetransEntry) GetSrcIp() []byte {
	if x != nil {
		return x.SrcIp
	}
	return nil
}

func (x *RetransEntry) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *RetransEntry) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *RetransEntry) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *RetransEntry) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RTTEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIp         []byte                 `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp         []byte                 `protobuf:"bytes,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort       uint32                 `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort       uint32                 `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	SumUs         uint64                 `protobuf:"varint,5,opt,name=sum_us,json=sumUs,proto3" json:"sum_us,omitempty"`
	Count         uint64                 `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	MinUs         uint32                 `protobuf:"varint,7,opt,name=min_us,json=minUs,proto3" json:"min_us,omitempty"`
	MaxUs         uint32                 `protobuf:"varint,8,opt,name=max_us,json=maxUs,proto3" json:"max_us,omitempty"`
	Hist          []uint32               `protobuf:"varint,9,rep,packed,name=hist,proto3" json:"hist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTTEntry) Reset() {
	*x = RTTEntry{}
	mi := &file_detective_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTTEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTTEntry) ProtoMessage() {}

func (x *RTTEntry) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTTEntry.ProtoReflect.Descriptor instead.
func (*RTTEntry) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{3}
}

func (x *RTTEntry) GetSrcIp() []byte {
	if x != nil {
		return x.SrcIp
	}
	return nil
}

func (x *RTTEntry) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *RTTEntry) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *RTTEntry) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *RTTEntry) GetSumUs() uint64 {
	if x != nil {
		return x.SumUs
	}
	return 0
}

func (x *RTTEntry) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RTTEntry) GetMinUs() uint32 {
	if x != nil {
		return x.MinUs
	}
	return 0
}

func (x *RTTEntry) GetMaxUs() uint32 {
	if x != nil {
		return x.MaxUs
	}
	return 0
}

func (x *RTTEntry) GetHist() []uint32 {
	if x != nil {
		return x.Hist
	}
	return nil
}

type DNSEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIp         []byte                 `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp         []byte                 `protobuf:"bytes,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	SumUs         uint64                 `protobuf:"varint,4,opt,name=sum_us,json=sumUs,proto3" json:"sum_us,omitempty"`
	MinUs         uint32                 `protobuf:"varint,5,opt,name=min_us,json=minUs,proto3" json:"min_us,omitempty"`
	MaxUs         uint32                 `protobuf:"varint,6,opt,name=max_us,json=maxUs,proto3" json:"max_us,omitempty"`
	Hist          []uint32               `protobuf:"varint,7,rep,packed,name=hist,proto3" json:"hist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSEntry) Reset() {
	*x = DNSEntry{}
	mi := &file_detective_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSEntry) ProtoMessage() {}

func (x *DNSEntry) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSEntry.ProtoReflect.Descriptor instead.
func (*DNSEntry) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{4}
}

func (x *DNSEntry) GetSrcIp() []byte {
	if x != nil {
		return x.SrcIp
	}
	return nil
}

func (x *DNSEntry) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *DNSEntry) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DNSEntry) GetSumUs() uint64 {
	if x != nil {
		return x.SumUs
	}
	return 0
}

func (x *DNSEntry) GetMinUs() uint32 {
	if x != nil {
		return x.MinUs
	}
	return 0
}

func (x *DNSEntry) GetMaxUs() uint32 {
	if x != nil {
		return x.MaxUs
	}
	return 0
}

func (x *DNSEntry) GetHist() []uint32 {
	if x != nil {
		return x.Hist
	}
	return nil
}

type AgentSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Flows         []*FlowEvent           `protobuf:"bytes,3,rep,name=flows,proto3" json:"flows,omitempty"`
	Throughput    []*ThroughputEntry     `protobuf:"bytes,4,rep,name=throughput,proto3" json:"throughput,omitempty"`
	Retrans       []*RetransEntry        `protobuf:"bytes,5,rep,name=retrans,proto3" json:"retrans,omitempty"`
	Rtt           []*RTTEntry            `protobuf:"bytes,6,rep,name=rtt,proto3" json:"rtt,omitempty"`
	Dns           []*DNSEntry            `protobuf:"bytes,7,rep,name=dns,proto3" json:"dns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSnapshot) Reset() {
	*x = AgentSnapshot{}
	mi := &file_detective_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSnapshot) ProtoMessage() {}

func (x *AgentSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSnapshot.ProtoReflect.Descriptor instead.
func (*AgentSnapshot) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{5}
}

func (x *AgentSnapshot) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *AgentSnapshot) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentSnapshot) GetFlows() []*FlowEvent {
	if x != nil {
		return x.Flows
	}
	return nil
}

func (x *AgentSnapshot) GetThroughput() []*ThroughputEntry {
	if x != nil {
		return x.Throughput
	}
	return nil
}

func (x *AgentSnapshot) GetRetrans() []*RetransEntry {
	if x != nil {
		return x.Retrans
	}
	return nil
}

func (x *AgentSnapshot) GetRtt() []*RTTEntry {
	if x != nil {
		return x.Rtt
	}
	return nil
}

func (x *AgentSnapshot) GetDns() []*DNSEntry {
	if x != nil {
		return x.Dns
	}
	return nil
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *AgentSnapshot         `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_detective_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotRequest) GetSnapshot() *AgentSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_detective_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{7}
}

func (x *SnapshotResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_detective_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{8}
}

type FlowList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flows         []*FlowEvent           `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowList) Reset() {
	*x = FlowList{}
	mi := &file_detective_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowList) ProtoMessage() {}

func (x *FlowList) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowList.ProtoReflect.Descriptor instead.
func (*FlowList) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{9}
}

func (x *FlowList) GetFlows() []*FlowEvent {
	if x != nil {
		return x.Flows
	}
	return nil
}

type TopTalker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,4,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,5,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	TxMbps        float64                `protobuf:"fixed64,6,opt,name=tx_mbps,json=txMbps,proto3" json:"tx_mbps,omitempty"`
	RxMbps        float64                `protobuf:"fixed64,7,opt,name=rx_mbps,json=rxMbps,proto3" json:"rx_mbps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopTalker) Reset() {
	*x = TopTalker{}
	mi := &file_detective_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopTalker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopTalker) ProtoMessage() {}

func (x *TopTalker) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopTalker.ProtoReflect.Descriptor instead.
func (*TopTalker) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{10}
}

func (x *TopTalker) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TopTalker) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *TopTalker) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *TopTalker) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *TopTalker) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *TopTalker) GetTxMbps() float64 {
	if x != nil {
		return x.TxMbps
	}
	return 0
}

func (x *TopTalker) GetRxMbps() float64 {
	if x != nil {
		return x.RxMbps
	}
	return 0
}

type TopTalkerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Talkers       []*TopTalker           `protobuf:"bytes,1,rep,name=talkers,proto3" json:"talkers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopTalkerList) Reset() {
	*x = TopTalkerList{}
	mi := &file_detective_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopTalkerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopTalkerList) ProtoMessage() {}

func (x *TopTalkerList) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopTalkerList.ProtoReflect.Descriptor instead.
func (*TopTalkerList) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{11}
}

func (x *TopTalkerList) GetTalkers() []*TopTalker {
	if x != nil {
		return x.Talkers
	}
	return nil
}

type RetransRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetransRecord) Reset() {
	*x = RetransRecord{}
	mi := &file_detective_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetransRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetransRecord) ProtoMessage() {}

func (x *RetransRecord) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetransRecord.ProtoReflect.Descriptor instead.
func (*RetransRecord) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{12}
}

func (x *RetransRecord) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RetransRecord) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RetransRecord) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RetransList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*RetransRecord       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetransList) Reset() {
	*x = RetransList{}
	mi := &file_detective_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetransList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetransList) ProtoMessage() {}

func (x *RetransList) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetransList.ProtoReflect.Descriptor instead.
func (*RetransList) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{13}
}

func (x *RetransList) GetRecords() []*RetransRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type LatencyRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	AvgUs         float64                `protobuf:"fixed64,3,opt,name=avg_us,json=avgUs,proto3" json:"avg_us,omitempty"`
	P95Us         float64                `protobuf:"fixed64,4,opt,name=p95_us,json=p95Us,proto3" json:"p95_us,omitempty"`
	P99Us         float64                `protobuf:"fixed64,5,opt,name=p99_us,json=p99Us,proto3" json:"p99_us,omitempty"`
	MinUs         uint32                 `protobuf:"varint,6,opt,name=min_us,json=minUs,proto3" json:"min_us,omitempty"`
	MaxUs         uint32                 `protobuf:"varint,7,opt,name=max_us,json=maxUs,proto3" json:"max_us,omitempty"`
	Samples       uint64                 `protobuf:"varint,8,opt,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyRecord) Reset() {
	*x = LatencyRecord{}
	mi := &file_detective_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyRecord) ProtoMessage() {}

func (x *LatencyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyRecord.ProtoReflect.Descriptor instead.
func (*LatencyRecord) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{14}
}

func (x *LatencyRecord) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LatencyRecord) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *LatencyRecord) GetAvgUs() float64 {
	if x != nil {
		return x.AvgUs
	}
	return 0
}

func (x *LatencyRecord) GetP95Us() float64 {
	if x != nil {
		return x.P95Us
	}
	return 0
}

func (x *LatencyRecord) GetP99Us() float64 {
	if x != nil {
		return x.P99Us
	}
	return 0
}

func (x *LatencyRecord) GetMinUs() uint32 {
	if x != nil {
		return x.MinUs
	}
	return 0
}

func (x *LatencyRecord) GetMaxUs() uint32 {
	if x != nil {
		return x.MaxUs
	}
	return 0
}

func (x *LatencyRecord) GetSamples() uint64 {
	if x != nil {
		return x.Samples
	}
	return 0
}

type LatencyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*LatencyRecord       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyList) Reset() {
	*x = LatencyList{}
	mi := &file_detective_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyList) ProtoMessage() {}

func (x *LatencyList) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyList.ProtoReflect.Descriptor instead.
func (*LatencyList) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{15}
}

func (x *LatencyList) GetRecords() []*LatencyRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type DNSRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	AvgUs         float64                `protobuf:"fixed64,3,opt,name=avg_us,json=avgUs,proto3" json:"avg_us,omitempty"`
	P95Us         float64                `protobuf:"fixed64,4,opt,name=p95_us,json=p95Us,proto3" json:"p95_us,omitempty"`
	P99Us         float64                `protobuf:"fixed64,5,opt,name=p99_us,json=p99Us,proto3" json:"p99_us,omitempty"`
	MinUs         uint32                 `protobuf:"varint,6,opt,name=min_us,json=minUs,proto3" json:"min_us,omitempty"`
	MaxUs         uint32                 `protobuf:"varint,7,opt,name=max_us,json=maxUs,proto3" json:"max_us,omitempty"`
	Queries       uint64                 `protobuf:"varint,8,opt,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRecord) Reset() {
	*x = DNSRecord{}
	mi := &file_detective_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecord) ProtoMessage() {}

func (x *DNSRecord) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecord.ProtoReflect.Descriptor instead.
func (*DNSRecord) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{16}
}

func (x *DNSRecord) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DNSRecord) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *DNSRecord) GetAvgUs() float64 {
	if x != nil {
		return x.AvgUs
	}
	return 0
}

func (x *DNSRecord) GetP95Us() float64 {
	if x != nil {
		return x.P95Us
	}
	return 0
}

func (x *DNSRecord) GetP99Us() float64 {
	if x != nil {
		return x.P99Us
	}
	return 0
}

func (x *DNSRecord) GetMinUs() uint32 {
	if x != nil {
		return x.MinUs
	}
	return 0
}

func (x *DNSRecord) GetMaxUs() uint32 {
	if x != nil {
		return x.MaxUs
	}
	return 0
}

func (x *DNSRecord) GetQueries() uint64 {
	if x != nil {
		return x.Queries
	}
	return 0
}

type DNSList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*DNSRecord           `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSList) Reset() {
	*x = DNSList{}
	mi := &file_detective_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSList) ProtoMessage() {}

func (x *DNSList) ProtoReflect() protoreflect.Message {
	mi := &file_detective_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSList.ProtoReflect.Descriptor instead.
func (*DNSList) Descriptor() ([]byte, []int) {
	return file_detective_proto_rawDescGZIP(), []int{17}
}

func (x *DNSList) GetRecords() []*DNSRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_detective_proto protoreflect.FileDescriptor

const file_detective_proto_rawDesc = "" +
	"\n" +
	"\x0fdetective.proto\x12\fdetective.v1\"\x95\x01\n" +
	"\tFlowEvent\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\fR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x02 \x01(\fR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x03 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x04 \x01(\rR\adstPort\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\rR\x03pid\x12\x12\n" +
	"\x04comm\x18\x06 \x01(\tR\x04comm\"\xab\x01\n" +
	"\x0fThroughputEntry\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\fR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x02 \x01(\fR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x03 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x04 \x01(\rR\adstPort\x12\x19\n" +
	"\btx_bytes\x18\x05 \x01(\x04R\atxBytes\x12\x19\n" +
	"\brx_bytes\x18\x06 \x01(\x04R\arxBytes\"\x88\x01\n" +
	"\fRetransEntry\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\fR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x02 \x01(\fR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x03 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x04 \x01(\rR\adstPort\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x04R\x05count\"\xdd\x01\n" +
	"\bRTTEntry\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\fR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x02 \x01(\fR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x03 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x04 \x01(\rR\adstPort\x12\x15\n" +
	"\x06sum_us\x18\x05 \x01(\x04R\x05sumUs\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x04R\x05count\x12\x15\n" +
	"\x06min_us\x18\a \x01(\rR\x05minUs\x12\x15\n" +
	"\x06max_us\x18\b \x01(\rR\x05maxUs\x12\x12\n" +
	"\x04hist\x18\t \x03(\rR\x04hist\"\xa7\x01\n" +
	"\bDNSEntry\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\fR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x02 \x01(\fR\x05dstIp\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\x12\x15\n" +
	"\x06sum_us\x18\x04 \x01(\x04R\x05sumUs\x12\x15\n" +
	"\x06min_us\x18\x05 \x01(\rR\x05minUs\x12\x15\n" +
	"\x06max_us\x18\x06 \x01(\rR\x05maxUs\x12\x12\n" +
	"\x04hist\x18\a \x03(\rR\x04hist\"\xc2\x02\n" +
	"\rAgentSnapshot\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12-\n" +
	"\x05flows\x18\x03 \x03(\v2\x17.detective.v1.FlowEventR\x05flows\x12=\n" +
	"\n" +
	"throughput\x18\x04 \x03(\v2\x1d.detective.v1.ThroughputEntryR\n" +
	"throughput\x124\n" +
	"\aretrans\x18\x05 \x03(\v2\x1a.detective.v1.RetransEntryR\aretrans\x12(\n" +
	"\x03rtt\x18\x06 \x03(\v2\x16.detective.v1.RTTEntryR\x03rtt\x12(\n" +
	"\x03dns\x18\a \x03(\v2\x16.detective.v1.DNSEntryR\x03dns\"J\n" +
	"\x0fSnapshotRequest\x127\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1b.detective.v1.AgentSnapshotR\bsnapshot\"\"\n" +
	"\x10SnapshotResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\a\n" +
	"\x05Empty\"9\n" +
	"\bFlowList\x12-\n" +
	"\x05flows\x18\x01 \x03(\v2\x17.detective.v1.FlowEventR\x05flows\"\xce\x01\n" +
	"\tTopTalker\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x04R\atxBytes\x12\x19\n" +
	"\brx_bytes\x18\x04 \x01(\x04R\arxBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x05 \x01(\x04R\n" +
	"totalBytes\x12\x17\n" +
	"\atx_mbps\x18\x06 \x01(\x01R\x06txMbps\x12\x17\n" +
	"\arx_mbps\x18\a \x01(\x01R\x06rxMbps\"B\n" +
	"\rTopTalkerList\x121\n" +
	"\atalkers\x18\x01 \x03(\v2\x17.detective.v1.TopTalkerR\atalkers\"_\n" +
	"\rRetransRecord\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\"D\n" +
	"\vRetransList\x125\n" +
	"\arecords\x18\x01 \x03(\v2\x1b.detective.v1.RetransRecordR\arecords\"\xd6\x01\n" +
	"\rLatencyRecord\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x15\n" +
	"\x06avg_us\x18\x03 \x01(\x01R\x05avgUs\x12\x15\n" +
	"\x06p95_us\x18\x04 \x01(\x01R\x05p95Us\x12\x15\n" +
	"\x06p99_us\x18\x05 \x01(\x01R\x05p99Us\x12\x15\n" +
	"\x06min_us\x18\x06 \x01(\rR\x05minUs\x12\x15\n" +
	"\x06max_us\x18\a \x01(\rR\x05maxUs\x12\x18\n" +
	"\asamples\x18\b \x01(\x04R\asamples\"D\n" +
	"\vLatencyList\x125\n" +
	"\arecords\x18\x01 \x03(\v2\x1b.detective.v1.LatencyRecordR\arecords\"\xd2\x01\n" +
	"\tDNSRecord\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x15\n" +
	"\x06avg_us\x18\x03 \x01(\x01R\x05avgUs\x12\x15\n" +
	"\x06p95_us\x18\x04 \x01(\x01R\x05p95Us\x12\x15\n" +
	"\x06p99_us\x18\x05 \x01(\x01R\x05p99Us\x12\x15\n" +
	"\x06min_us\x18\x06 \x01(\rR\x05minUs\x12\x15\n" +
	"\x06max_us\x18\a \x01(\rR\x05maxUs\x12\x18\n" +
	"\aqueries\x18\b \x01(\x04R\aqueries\"<\n" +
	"\aDNSList\x121\n" +
	"\arecords\x18\x01 \x03(\v2\x17.detective.v1.DNSRecordR\arecords2]\n" +
	"\fAgentService\x12M\n" +
	"\fSendSnapshot\x12\x1d.detective.v1.SnapshotRequest\x1a\x1e.detective.v1.SnapshotResponse2\xb9\x02\n" +
	"\x10DetectiveService\x127\n" +
	"\bGetFlows\x12\x13.detective.v1.Empty\x1a\x16.detective.v1.FlowList\x12:\n" +
	"\x06GetTop\x12\x13.detective.v1.Empty\x1a\x1b.detective.v1.TopTalkerList\x12<\n" +
	"\n" +
	"GetRetrans\x12\x13.detective.v1.Empty\x1a\x19.detective.v1.RetransList\x12<\n" +
	"\n" +
	"GetLatency\x12\x13.detective.v1.Empty\x1a\x19.detective.v1.LatencyList\x124\n" +
	"\x06GetDNS\x12\x13.detective.v1.Empty\x1a\x15.detective.v1.DNSListB0Z.Kubernetes-plugin/api/detective/v1;detectivev1b\x06proto3"

var (
	file_detective_proto_rawDescOnce sync.Once
	file_detective_proto_rawDescData []byte
)

func file_detective_proto_rawDescGZIP() []byte {
	file_detective_proto_rawDescOnce.Do(func() {
		file_detective_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_detective_proto_rawDesc), len(file_detective_proto_rawDesc)))
	})
	return file_detective_proto_rawDescData
}

var file_detective_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_detective_proto_goTypes = []any{
	(*FlowEvent)(nil),        // 0: detective.v1.FlowEvent
	(*ThroughputEntry)(nil),  // 1: detective.v1.ThroughputEntry
	(*RetransEntry)(nil),     // 2: detective.v1.RetransEntry
	(*RTTEntry)(nil),         // 3: detective.v1.RTTEntry
	(*DNSEntry)(nil),         // 4: detective.v1.DNSEntry
	(*AgentSnapshot)(nil),    // 5: detective.v1.AgentSnapshot
	(*SnapshotRequest)(nil),  // 6: detective.v1.SnapshotRequest
	(*SnapshotResponse)(nil), // 7: detective.v1.SnapshotResponse
	(*Empty)(nil),            // 8: detective.v1.Empty
	(*FlowList)(nil),         // 9: detective.v1.FlowList
	(*TopTalker)(nil),        // 10: detective.v1.TopTalker
	(*TopTalkerList)(nil),    // 11: detective.v1.TopTalkerList
	(*RetransRecord)(nil),    // 12: detective.v1.RetransRecord
	(*RetransList)(nil),      // 13: detective.v1.RetransList
	(*LatencyRecord)(nil),    // 14: detective.v1.LatencyRecord
	(*LatencyList)(nil),      // 15: detective.v1.LatencyList
	(*DNSRecord)(nil),        // 16: detective.v1.DNSRecord
	(*DNSList)(nil),          // 17: detective.v1.DNSList
}
var file_detective_proto_depIdxs = []int32{
	0,  // 0: detective.v1.AgentSnapshot.flows:type_name -> detective.v1.FlowEvent
	1,  // 1: detective.v1.AgentSnapshot.throughput:type_name -> detective.v1.ThroughputEntry
	2,  // 2: detective.v1.AgentSnapshot.retrans:type_name -> detective.v1.RetransEntry
	3,  // 3: detective.v1.AgentSnapshot.rtt:type_name -> detective.v1.RTTEntry
	4,  // 4: detective.v1.AgentSnapshot.dns:type_name -> detective.v1.DNSEntry
	5,  // 5: detective.v1.SnapshotRequest.snapshot:type_name -> detective.v1.AgentSnapshot
	0,  // 6: detective.v1.FlowList.flows:type_name -> detective.v1.FlowEvent
	10, // 7: detective.v1.TopTalkerList.talkers:type_name -> detective.v1.TopTalker
	12, // 8: detective.v1.RetransList.records:type_name -> detective.v1.RetransRecord
	14, // 9: detective.v1.LatencyList.records:type_name -> detective.v1.LatencyRecord
	16, // 10: detective.v1.DNSList.records:type_name -> detective.v1.DNSRecord
	6,  // 11: detective.v1.AgentService.SendSnapshot:input_type -> detective.v1.SnapshotRequest
	8,  // 12: detective.v1.DetectiveService.GetFlows:input_type -> detective.v1.Empty
	8,  // 13: detective.v1.DetectiveService.GetTop:input_type -> detective.v1.Empty
	8,  // 14: detective.v1.DetectiveService.GetRetrans:input_type -> detective.v1.Empty
	8,  // 15: detective.v1.DetectiveService.GetLatency:input_type -> detective.v1.Empty
	8,  // 16: detective.v1.DetectiveService.GetDNS:input_type -> detective.v1.Empty
	7,  // 17: detective.v1.AgentService.SendSnapshot:output_type -> detective.v1.SnapshotResponse
	9,  // 18: detective.v1.DetectiveService.GetFlows:output_type -> detective.v1.FlowList
	11, // 19: detective.v1.DetectiveService.GetTop:output_type -> detective.v1.TopTalkerList
	13, // 20: detective.v1.DetectiveService.GetRetrans:output_type -> detective.v1.RetransList
	15, // 21: detective.v1.DetectiveService.GetLatency:output_type -> detective.v1.LatencyList
	17, // 22: detective.v1.DetectiveService.GetDNS:output_type -> detective.v1.DNSList
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_detective_proto_init() }
func file_detective_proto_init() {
	if File_detective_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_detective_proto_rawDesc), len(file_detective_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_detective_proto_goTypes,
		DependencyIndexes: file_detective_proto_depIdxs,
		MessageInfos:      file_detective_proto_msgTypes,
	}.Build()
	File_detective_proto = out.File
	file_detective_proto_goTypes = nil
	file_detective_proto_depIdxs = nil
}
